export const EventAccessActionTypes = {
  JOIN_SESSION: 'JOIN_SESSION',
  EVENT_ACCESS_DEFAULT: 'EVENT_ACCESS_DEFAULT',
  REMOVE_FROM_EVENT: 'REMOVE_FROM_EVENT',
  SET_REMOVED_STATE_TO_DEFAULT: 'SET_REMOVED_STATE_TO_DEFAULT',
  CREATE_EVENT_START: 'CREATE_EVENT_START',
  CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
  CREATE_EVENT_FAILURE: 'CREATE_EVENT_FAILURE',
  JOIN_EVENT_START: 'JOIN_EVENT_START',
  JOIN_EVENT_SUCCESS: 'JOIN_EVENT_SUCCESS',
  JOIN_EVENT_FAILURE: 'JOIN_EVENT_FAILURE',
  SET_EVENT_INFORMATION_FETCHED: 'SET_EVENT_INFORMATION_FETCHED'
}