const SocketActionTypes = {
  INITIALIZE_SOCKET_CHANNEL: 'INITIALIZE_SOCKET_CHANNEL',
  SOCKET_CONNECTED: 'SOCKET_CONNECTED',
  DISCONNECT_SOCKET: 'DISCONNECT_SOCKET',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
  SOCKET_RECONNECTED: 'SOCKET_RECONNECTED',
  SOCKET_RECONNECTED_DEFAULT: 'SOCKET_RECONNECTED_DEFAULT',
  UPDATE_PACKET_STATUS: 'UPDATE_PACKET_STATUS',
  PULL_DATA_FROM_SERVER_FALSE: 'PULL_DATA_FROM_SERVER_FALSE'
}

export default SocketActionTypes;