const UserActionTypes = {
  SIGN_OUT: 'SIGN_OUT',
  UPDATE_EXISTING_EVENT_INFO: 'UPDATE_EXISTING_EVENT_INFO',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  EDIT_PROFILE_AND_PICTURE_START: 'EDIT_PROFILE_AND_PICTURE_START',
  EDIT_PROFILE_AND_PICTURE_SUCCESS: 'EDIT_PROFILE_AND_PICTURE_SUCCESS',
  EDIT_PROFILE_AND_PICTURE_FAILURE: 'EDIT_PROFILE_AND_PICTURE_FAILURE',
  EDIT_PROFILE_START: 'EDIT_PROFILE_START',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',
  CHANGE_ACTIVE_STATE_START: 'CHANGE_ACTIVE_STATE_START',
  CHANGE_ACTIVE_STATE_SUCCESS: 'CHANGE_ACTIVE_STATE_SUCCESS',
  CHANGE_ACTIVE_STATE_FAILURE: 'CHANGE_ACTIVE_STATE_FAILURE',
  DELETE_EVENT_START: 'DELETE_EVENT_START',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_FAILURE: 'DELETE_EVENT_FAILURE',
  SUBMIT_EMAIL_START: 'SUBMIT_EMAIL_START',
  SUBMIT_EMAIL_SUCCESS: 'SUBMIT_EMAIL_SUCCESS',
  SUBMIT_EMAIL_FAILURE: 'SUBMIT_EMAIL_FAILURE'
}

export default UserActionTypes;